baseURL = "https://erwinkn.com/"
languageCode = "en-us"
title = "Erwin Kuhn"
author = "Erwin Kuhn"

[params]
description = "I write code for the climate. Previously: food photographer, (involuntary) influencer and data markets researcher."
image="/img/default.png"
imageAlt="Homepage of Erwin Kuhn's website"

[menu]
    [[menu.main]]
    identifier = "Climate"
    name = "Climate"
    url = "/climate/"
    weight = "-20"


    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "10"

    [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = "20"

    [[menu.main]]
    identifier="tech"
    name = "Tech"
    url = "/tech/"
    weight = "-10"

[taxonomies]
category = "categories"
tag = "tags"

[build]
writeStats = true

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = true
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe=true

