baseURL = "https://erwinkn.com/"
languageCode = "en-us"
title = "Erwin Kuhn"
author = "Erwin Kuhn"

[params]
description = "I write code for the climate. Previously: food photographer, (involuntary) influencer and data markets researcher."
image="/img/default.png"
imageAlt="Homepage of Erwin Kuhn's website"

[menu]
    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"

    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

    [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"

    [[menu.main]]
    identifier="tricks"
    name = "Tricks"
    url = "/tricks/"

[taxonomies]
category = "categories"
tag = "tags"

[build]
writeStats = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe=true

